options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  # Defina no Trigger (recommended) com a URL pública do backend/BFF em produção.
  # Exemplo: https://assistente-api-xxxxx-uc.a.run.app
  _NEXT_PUBLIC_API_BASE_URL: ""
  # Defina no Trigger com o serviço/região do Cloud Run.
  _CLOUD_RUN_SERVICE_WEB: "assistente-web"
  _CLOUD_RUN_SERVICE_API: "assistente-api"
  _CLOUD_RUN_REGION: "us-central1"

steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -ceu
      - |
        if [[ -z "${_NEXT_PUBLIC_API_BASE_URL}" ]]; then
          echo "ERROR: defina substitution _NEXT_PUBLIC_API_BASE_URL (URL pública da API/BFF)."
          exit 1
        fi
        if [[ "${_NEXT_PUBLIC_API_BASE_URL}" =~ ^https?://(localhost|127\\.0\\.0\\.1) ]]; then
          echo "ERROR: _NEXT_PUBLIC_API_BASE_URL não pode ser localhost/127.0.0.1 em produção."
          exit 1
        fi

  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-f",
        "web/Dockerfile",
        "--target",
        "runner",
        "--build-arg",
        "NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL}",
        "-t",
        "gcr.io/$PROJECT_ID/assistente-web:$COMMIT_SHA",
        "web",
      ]

  # O push precisa acontecer ANTES do deploy (o bloco `images:` só faz push ao final do build).
  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/assistente-web:$COMMIT_SHA"]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_CLOUD_RUN_SERVICE_WEB}",
        "--image",
        "gcr.io/$PROJECT_ID/assistente-web:$COMMIT_SHA",
        "--region",
        "${_CLOUD_RUN_REGION}",
        "--platform",
        "managed",
        "--port",
        "8080",
        "--set-env-vars",
        "NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL}",
      ]

  # Build da API
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-f",
        "backend/Dockerfile",
        "--target",
        "runner",
        "-t",
        "gcr.io/$PROJECT_ID/assistente-api:$COMMIT_SHA",
        "backend",
      ]

  # Push da imagem da API
  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/assistente-api:$COMMIT_SHA"]

  # Deploy da API
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_CLOUD_RUN_SERVICE_API}",
        "--image",
        "gcr.io/$PROJECT_ID/assistente-api:$COMMIT_SHA",
        "--region",
        "${_CLOUD_RUN_REGION}",
        "--platform",
        "managed",
        "--port",
        "8080",
      ]

images:
  - 'gcr.io/$PROJECT_ID/assistente-web:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/assistente-api:$COMMIT_SHA'
