// <auto-generated />
using System;
using AssistenteExecutivo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssistenteExecutivo.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251225013630_RemovePaymentFieldsFromNotesAndRelationships")]
    partial class RemovePaymentFieldsFromNotesAndRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.CaptureJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AudioSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("AudioTranscript")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AudioTranscript_Json");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("IX_CaptureJobs_ContactId");

                    b.HasIndex("MediaId");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_CaptureJobs_OwnerUserId");

                    b.HasIndex("RequestedAt")
                        .HasDatabaseName("IX_CaptureJobs_RequestedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_CaptureJobs_Status");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_CaptureJobs_Type");

                    b.ToTable("CaptureJobs", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Domains")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Domains");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Notes");

                    b.HasKey("CompanyId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Companies_Name");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ContactId");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Company");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("JobTitle");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OwnerUserId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("ContactId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Contacts_CreatedAt");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Contacts_IsDeleted");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_Contacts_OwnerUserId");

                    b.HasIndex("OwnerUserId", "IsDeleted")
                        .HasDatabaseName("IX_Contacts_OwnerUserId_IsDeleted");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.CreditPackage", b =>
                {
                    b.Property<Guid>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PackageId");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("Currency");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("PackageId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_CreditPackages_IsActive");

                    b.ToTable("CreditPackages", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.CreditTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TransactionId");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("IdempotencyKey");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("OccurredAt");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OwnerUserId");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Reason");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.HasKey("TransactionId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_CreditTransactions_IdempotencyKey")
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("IX_CreditTransactions_OccurredAt");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_CreditTransactions_OwnerUserId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_CreditTransactions_Type");

                    b.ToTable("CreditTransactions", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.CreditWallet", b =>
                {
                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OwnerUserId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.HasKey("OwnerUserId");

                    b.ToTable("CreditWallets", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.LoginAuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("UserId");

                    b.ToTable("LoginAuditEntries", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.MediaAsset", b =>
                {
                    b.Property<Guid>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("FileContent")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("FileContent");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MediaId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_MediaAssets_CreatedAt");

                    b.HasIndex("Kind")
                        .HasDatabaseName("IX_MediaAssets_Kind");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_MediaAssets_OwnerUserId");

                    b.ToTable("MediaAssets", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("StructuredData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("NoteId");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("IX_Notes_AuthorId");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("IX_Notes_ContactId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Notes_CreatedAt");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Notes_Type");

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Plan", b =>
                {
                    b.Property<Guid>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PlanId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("Currency");

                    b.Property<bool>("Highlighted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Highlighted");

                    b.Property<int>("Interval")
                        .HasColumnType("int")
                        .HasColumnName("Interval");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("_features")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Features");

                    b.HasKey("PlanId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Plans_IsActive");

                    b.HasIndex("IsActive", "Interval")
                        .HasDatabaseName("IX_Plans_IsActive_Interval");

                    b.ToTable("Plans", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Relationship", b =>
                {
                    b.Property<Guid>("RelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RelationshipId");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsConfirmed");

                    b.Property<Guid>("SourceContactId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SourceContactId");

                    b.Property<float>("Strength")
                        .HasColumnType("real")
                        .HasColumnName("Strength");

                    b.Property<Guid>("TargetContactId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TargetContactId");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Type");

                    b.HasKey("RelationshipId");

                    b.HasIndex("SourceContactId")
                        .HasDatabaseName("IX_Relationships_SourceContactId");

                    b.HasIndex("TargetContactId")
                        .HasDatabaseName("IX_Relationships_TargetContactId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Relationships_Type");

                    b.HasIndex("SourceContactId", "TargetContactId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Relationships_SourceContactId_TargetContactId");

                    b.ToTable("Relationships", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreditBalance")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Notifications.EmailOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NextRetryAt");

                    b.HasIndex("Status");

                    b.ToTable("EmailOutboxMessages", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Notifications.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TemplateType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TemplateType");

                    b.HasIndex("TemplateType", "IsActive");

                    b.ToTable("EmailTemplates", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.CaptureJob", b =>
                {
                    b.HasOne("AssistenteExecutivo.Domain.Entities.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssistenteExecutivo.Domain.Entities.MediaAsset", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssistenteExecutivo.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AssistenteExecutivo.Domain.ValueObjects.OcrExtract", "CardScanResult", b1 =>
                        {
                            b1.Property<Guid>("CaptureJobJobId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Company")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("CardScanResult_Company");

                            b1.Property<string>("ConfidenceScores")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CardScanResult_ConfidenceScores");

                            b1.Property<string>("Email")
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("CardScanResult_Email");

                            b1.Property<string>("JobTitle")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("CardScanResult_JobTitle");

                            b1.Property<string>("Name")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("CardScanResult_Name");

                            b1.Property<string>("Phone")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("CardScanResult_Phone");

                            b1.HasKey("CaptureJobJobId");

                            b1.ToTable("CaptureJobs");

                            b1.WithOwner()
                                .HasForeignKey("CaptureJobJobId");
                        });

                    b.OwnsMany("AssistenteExecutivo.Domain.ValueObjects.ExtractedTask", "ExtractedTasks", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Description");

                            b1.Property<DateTime?>("DueDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("DueDate");

                            b1.Property<Guid>("JobId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Priority")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Priority");

                            b1.HasKey("Id");

                            b1.HasIndex("JobId");

                            b1.ToTable("CaptureJobExtractedTasks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.Navigation("CardScanResult");

                    b.Navigation("ExtractedTasks");
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Contact", b =>
                {
                    b.OwnsMany("AssistenteExecutivo.Domain.ValueObjects.EmailAddress", "Emails", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Email");

                            b1.HasKey("ContactId", "Value");

                            b1.ToTable("ContactEmails", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.OwnsOne("AssistenteExecutivo.Domain.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LastName");

                            b1.HasKey("ContactId");

                            b1.ToTable("Contacts");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.OwnsOne("AssistenteExecutivo.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AddressCity");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AddressCountry");

                            b1.Property<string>("State")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AddressState");

                            b1.Property<string>("Street")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("AddressStreet");

                            b1.Property<string>("ZipCode")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("AddressZipCode");

                            b1.HasKey("ContactId");

                            b1.ToTable("Contacts");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.OwnsMany("AssistenteExecutivo.Domain.ValueObjects.PhoneNumber", "Phones", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Number")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Number");

                            b1.Property<string>("FormattedNumber")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("FormattedNumber");

                            b1.HasKey("ContactId", "Number");

                            b1.ToTable("ContactPhones", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.OwnsMany("AssistenteExecutivo.Domain.ValueObjects.Tag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Tag");

                            b1.HasKey("ContactId", "Value");

                            b1.ToTable("ContactTags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Emails");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Phones");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.CreditTransaction", b =>
                {
                    b.HasOne("AssistenteExecutivo.Domain.Entities.CreditWallet", null)
                        .WithMany("Transactions")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AssistenteExecutivo.Domain.ValueObjects.CreditAmount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("CreditTransactionTransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.HasKey("CreditTransactionTransactionId");

                            b1.ToTable("CreditTransactions");

                            b1.WithOwner()
                                .HasForeignKey("CreditTransactionTransactionId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.CreditWallet", b =>
                {
                    b.HasOne("AssistenteExecutivo.Domain.Entities.UserProfile", null)
                        .WithOne()
                        .HasForeignKey("AssistenteExecutivo.Domain.Entities.CreditWallet", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.MediaAsset", b =>
                {
                    b.OwnsOne("AssistenteExecutivo.Domain.ValueObjects.MediaRef", "MediaRef", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetMediaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("Hash");

                            b1.Property<string>("MimeType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("MimeType");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("SizeBytes");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("StorageKey");

                            b1.HasKey("MediaAssetMediaId");

                            b1.ToTable("MediaAssets");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetMediaId");
                        });

                    b.Navigation("MediaRef")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Note", b =>
                {
                    b.HasOne("AssistenteExecutivo.Domain.Entities.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Plan", b =>
                {
                    b.OwnsOne("AssistenteExecutivo.Domain.ValueObjects.PlanLimits", "Limits", b1 =>
                        {
                            b1.Property<Guid>("PlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("Contacts")
                                .HasColumnType("int")
                                .HasColumnName("LimitsContacts");

                            b1.Property<int?>("CreditsPerMonth")
                                .HasColumnType("int")
                                .HasColumnName("LimitsCreditsPerMonth");

                            b1.Property<int?>("Notes")
                                .HasColumnType("int")
                                .HasColumnName("LimitsNotes");

                            b1.Property<decimal?>("StorageGB")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("LimitsStorageGB");

                            b1.HasKey("PlanId");

                            b1.ToTable("Plans");

                            b1.WithOwner()
                                .HasForeignKey("PlanId");
                        });

                    b.Navigation("Limits");
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Relationship", b =>
                {
                    b.HasOne("AssistenteExecutivo.Domain.Entities.Contact", null)
                        .WithMany("Relationships")
                        .HasForeignKey("SourceContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssistenteExecutivo.Domain.Entities.Contact", null)
                        .WithMany()
                        .HasForeignKey("TargetContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.UserProfile", b =>
                {
                    b.OwnsOne("AssistenteExecutivo.Domain.ValueObjects.PersonName", "DisplayName", b1 =>
                        {
                            b1.Property<Guid>("UserProfileUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LastName");

                            b1.HasKey("UserProfileUserId");

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileUserId");
                        });

                    b.OwnsOne("AssistenteExecutivo.Domain.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserProfileUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Email");

                            b1.HasKey("UserProfileUserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileUserId");
                        });

                    b.OwnsOne("AssistenteExecutivo.Domain.ValueObjects.KeycloakSubject", "KeycloakSubject", b1 =>
                        {
                            b1.Property<Guid>("UserProfileUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("KeycloakSubject");

                            b1.HasKey("UserProfileUserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileUserId");
                        });

                    b.Navigation("DisplayName")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("KeycloakSubject")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Contact", b =>
                {
                    b.Navigation("Relationships");
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.CreditWallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
