// <auto-generated />
using System;
using AssistenteExecutivo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssistenteExecutivo.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.AgentConfiguration", b =>
                {
                    b.Property<Guid>("ConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ConfigurationId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("OcrPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("OcrPrompt");

                    b.Property<string>("TranscriptionPrompt")
                        .HasColumnType("text")
                        .HasColumnName("TranscriptionPrompt");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("WorkflowPrompt")
                        .HasColumnType("text")
                        .HasColumnName("WorkflowPrompt");

                    b.HasKey("ConfigurationId");

                    b.HasIndex("ConfigurationId")
                        .IsUnique()
                        .HasDatabaseName("IX_AgentConfigurations_ConfigurationId");

                    b.ToTable("AgentConfigurations", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.CaptureJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("AudioTranscript")
                        .HasColumnType("text")
                        .HasColumnName("AudioTranscript_Json");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("JobId");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("IX_CaptureJobs_ContactId");

                    b.HasIndex("MediaId");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_CaptureJobs_OwnerUserId");

                    b.HasIndex("RequestedAt")
                        .HasDatabaseName("IX_CaptureJobs_RequestedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_CaptureJobs_Status");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_CaptureJobs_Type");

                    b.ToTable("CaptureJobs", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CompanyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Domains")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Domains");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("Notes");

                    b.HasKey("CompanyId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Companies_Name");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ContactId");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Company");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("JobTitle");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("OwnerUserId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("ContactId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Contacts_CreatedAt");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Contacts_IsDeleted");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_Contacts_OwnerUserId");

                    b.HasIndex("OwnerUserId", "IsDeleted")
                        .HasDatabaseName("IX_Contacts_OwnerUserId_IsDeleted");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.CreditPackage", b =>
                {
                    b.Property<Guid>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PackageId");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("Currency");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("PackageId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_CreditPackages_IsActive");

                    b.ToTable("CreditPackages", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.CreditTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TransactionId");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("IdempotencyKey");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OccurredAt");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("OwnerUserId");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Reason");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("Type");

                    b.HasKey("TransactionId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_CreditTransactions_IdempotencyKey")
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("IX_CreditTransactions_OccurredAt");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_CreditTransactions_OwnerUserId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_CreditTransactions_Type");

                    b.ToTable("CreditTransactions", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.CreditWallet", b =>
                {
                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("OwnerUserId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.HasKey("OwnerUserId");

                    b.ToTable("CreditWallets", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.DraftDocument", b =>
                {
                    b.Property<Guid>("DraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("DraftId");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("CompanyId");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("ContactId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer")
                        .HasColumnName("DocumentType");

                    b.Property<Guid?>("LetterheadId")
                        .HasColumnType("uuid")
                        .HasColumnName("LetterheadId");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("OwnerUserId");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("TemplateId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("DraftId");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_DraftDocuments_CompanyId");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("IX_DraftDocuments_ContactId");

                    b.HasIndex("DocumentType")
                        .HasDatabaseName("IX_DraftDocuments_DocumentType");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_DraftDocuments_OwnerUserId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_DraftDocuments_Status");

                    b.HasIndex("OwnerUserId", "Status")
                        .HasDatabaseName("IX_DraftDocuments_OwnerUserId_Status");

                    b.ToTable("DraftDocuments", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Letterhead", b =>
                {
                    b.Property<Guid>("LetterheadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("LetterheadId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("DesignData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DesignData");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("OwnerUserId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("LetterheadId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Letterheads_IsActive");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_Letterheads_OwnerUserId");

                    b.HasIndex("OwnerUserId", "IsActive")
                        .HasDatabaseName("IX_Letterheads_OwnerUserId_IsActive");

                    b.ToTable("Letterheads", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.LoginAuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("UserId");

                    b.ToTable("LoginAuditEntries", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.MediaAsset", b =>
                {
                    b.Property<Guid>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("FileContent")
                        .HasColumnType("bytea")
                        .HasColumnName("FileContent");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("MediaId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_MediaAssets_CreatedAt");

                    b.HasIndex("Kind")
                        .HasDatabaseName("IX_MediaAssets_Kind");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_MediaAssets_OwnerUserId");

                    b.ToTable("MediaAssets", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("StructuredData")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("NoteId");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("IX_Notes_AuthorId");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("IX_Notes_ContactId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Notes_CreatedAt");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Notes_Type");

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Plan", b =>
                {
                    b.Property<Guid>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PlanId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("Currency");

                    b.Property<bool>("Highlighted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("Highlighted");

                    b.Property<int>("Interval")
                        .HasColumnType("integer")
                        .HasColumnName("Interval");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("_features")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("Features");

                    b.HasKey("PlanId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Plans_IsActive");

                    b.HasIndex("IsActive", "Interval")
                        .HasDatabaseName("IX_Plans_IsActive_Interval");

                    b.ToTable("Plans", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Relationship", b =>
                {
                    b.Property<Guid>("RelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("RelationshipId");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsConfirmed");

                    b.Property<Guid>("SourceContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceContactId");

                    b.Property<float>("Strength")
                        .HasColumnType("real")
                        .HasColumnName("Strength");

                    b.Property<Guid>("TargetContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("TargetContactId");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Type");

                    b.HasKey("RelationshipId");

                    b.HasIndex("SourceContactId")
                        .HasDatabaseName("IX_Relationships_SourceContactId");

                    b.HasIndex("TargetContactId")
                        .HasDatabaseName("IX_Relationships_TargetContactId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Relationships_Type");

                    b.HasIndex("SourceContactId", "TargetContactId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Relationships_SourceContactId_TargetContactId");

                    b.ToTable("Relationships", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Reminder", b =>
                {
                    b.Property<Guid>("ReminderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ReminderId");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("ContactId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("OwnerUserId");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("Reason");

                    b.Property<DateTime>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ScheduledFor");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<string>("SuggestedMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("SuggestedMessage");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("ReminderId");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("IX_Reminders_ContactId");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_Reminders_OwnerUserId");

                    b.HasIndex("ScheduledFor")
                        .HasDatabaseName("IX_Reminders_ScheduledFor");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Reminders_Status");

                    b.HasIndex("OwnerUserId", "Status")
                        .HasDatabaseName("IX_Reminders_OwnerUserId_Status");

                    b.HasIndex("Status", "ScheduledFor")
                        .HasDatabaseName("IX_Reminders_Status_ScheduledFor");

                    b.ToTable("Reminders", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Template", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TemplateId");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("OwnerUserId");

                    b.Property<string>("PlaceholdersSchema")
                        .HasColumnType("text")
                        .HasColumnName("PlaceholdersSchema");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("Type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("TemplateId");

                    b.HasIndex("Active")
                        .HasDatabaseName("IX_Templates_Active");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_Templates_OwnerUserId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Templates_Type");

                    b.HasIndex("OwnerUserId", "Active")
                        .HasDatabaseName("IX_Templates_OwnerUserId_Active");

                    b.HasIndex("OwnerUserId", "Type", "Active")
                        .HasDatabaseName("IX_Templates_OwnerUserId_Type_Active");

                    b.ToTable("Templates", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreditBalance")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Workflow", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("WorkflowId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("Description");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("IdempotencyKey");

                    b.Property<string>("N8nWorkflowId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("N8nWorkflowId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("OwnerUserId");

                    b.Property<string>("SpecJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("SpecJson");

                    b.Property<int>("SpecVersion")
                        .HasColumnType("integer")
                        .HasColumnName("SpecVersion");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("WorkflowId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_Workflows_IdempotencyKey")
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.HasIndex("N8nWorkflowId")
                        .HasDatabaseName("IX_Workflows_N8nWorkflowId");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_Workflows_OwnerUserId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Workflows_Status");

                    b.HasIndex("OwnerUserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Workflows_OwnerUserId_Name");

                    b.HasIndex("OwnerUserId", "Status")
                        .HasDatabaseName("IX_Workflows_OwnerUserId_Status");

                    b.ToTable("Workflows", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.WorkflowExecution", b =>
                {
                    b.Property<Guid>("ExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ExecutionId");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CompletedAt");

                    b.Property<int?>("CurrentStepIndex")
                        .HasColumnType("integer")
                        .HasColumnName("CurrentStepIndex");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("ErrorMessage");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("IdempotencyKey");

                    b.Property<string>("InputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("InputJson");

                    b.Property<string>("N8nExecutionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("N8nExecutionId");

                    b.Property<string>("OutputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("OutputJson");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("OwnerUserId");

                    b.Property<int>("SpecVersionUsed")
                        .HasColumnType("integer")
                        .HasColumnName("SpecVersionUsed");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartedAt");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("WorkflowId");

                    b.HasKey("ExecutionId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkflowExecutions_IdempotencyKey")
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.HasIndex("N8nExecutionId")
                        .HasDatabaseName("IX_WorkflowExecutions_N8nExecutionId");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_WorkflowExecutions_OwnerUserId");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("IX_WorkflowExecutions_StartedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_WorkflowExecutions_Status");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("IX_WorkflowExecutions_WorkflowId");

                    b.HasIndex("OwnerUserId", "Status")
                        .HasDatabaseName("IX_WorkflowExecutions_OwnerUserId_Status");

                    b.ToTable("WorkflowExecutions", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Notifications.EmailOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NextRetryAt");

                    b.HasIndex("Status");

                    b.ToTable("EmailOutboxMessages", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Notifications.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TemplateType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TemplateType");

                    b.HasIndex("TemplateType", "IsActive");

                    b.ToTable("EmailTemplates", (string)null);
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.CaptureJob", b =>
                {
                    b.HasOne("AssistenteExecutivo.Domain.Entities.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssistenteExecutivo.Domain.Entities.MediaAsset", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssistenteExecutivo.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AssistenteExecutivo.Domain.ValueObjects.OcrExtract", "CardScanResult", b1 =>
                        {
                            b1.Property<Guid>("CaptureJobJobId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AiRawResponse")
                                .HasColumnType("text")
                                .HasColumnName("CardScanResult_AiRawResponse");

                            b1.Property<string>("Company")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("CardScanResult_Company");

                            b1.Property<string>("ConfidenceScores")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CardScanResult_ConfidenceScores");

                            b1.Property<string>("Email")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("CardScanResult_Email");

                            b1.Property<string>("JobTitle")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("CardScanResult_JobTitle");

                            b1.Property<string>("Name")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("CardScanResult_Name");

                            b1.Property<string>("Phone")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("CardScanResult_Phone");

                            b1.Property<string>("RawText")
                                .HasColumnType("text")
                                .HasColumnName("CardScanResult_RawText");

                            b1.HasKey("CaptureJobJobId");

                            b1.ToTable("CaptureJobs");

                            b1.WithOwner()
                                .HasForeignKey("CaptureJobJobId");
                        });

                    b.OwnsMany("AssistenteExecutivo.Domain.ValueObjects.ExtractedTask", "ExtractedTasks", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Description");

                            b1.Property<DateTime?>("DueDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DueDate");

                            b1.Property<Guid>("JobId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Priority")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Priority");

                            b1.HasKey("Id");

                            b1.HasIndex("JobId");

                            b1.ToTable("CaptureJobExtractedTasks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.Navigation("CardScanResult");

                    b.Navigation("ExtractedTasks");
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Contact", b =>
                {
                    b.OwnsMany("AssistenteExecutivo.Domain.ValueObjects.EmailAddress", "Emails", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("Email");

                            b1.HasKey("ContactId", "Value");

                            b1.ToTable("ContactEmails", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.OwnsOne("AssistenteExecutivo.Domain.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("LastName");

                            b1.HasKey("ContactId");

                            b1.ToTable("Contacts");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.OwnsOne("AssistenteExecutivo.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("AddressCity");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("AddressCountry");

                            b1.Property<string>("State")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("AddressState");

                            b1.Property<string>("Street")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("AddressStreet");

                            b1.Property<string>("ZipCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("AddressZipCode");

                            b1.HasKey("ContactId");

                            b1.ToTable("Contacts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.OwnsMany("AssistenteExecutivo.Domain.ValueObjects.PhoneNumber", "Phones", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Number")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Number");

                            b1.Property<string>("FormattedNumber")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("FormattedNumber");

                            b1.HasKey("ContactId", "Number");

                            b1.ToTable("ContactPhones", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.OwnsMany("AssistenteExecutivo.Domain.ValueObjects.Tag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Tag");

                            b1.HasKey("ContactId", "Value");

                            b1.ToTable("ContactTags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Emails");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Phones");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.CreditTransaction", b =>
                {
                    b.HasOne("AssistenteExecutivo.Domain.Entities.CreditWallet", null)
                        .WithMany("Transactions")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AssistenteExecutivo.Domain.ValueObjects.CreditAmount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("CreditTransactionTransactionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.HasKey("CreditTransactionTransactionId");

                            b1.ToTable("CreditTransactions");

                            b1.WithOwner()
                                .HasForeignKey("CreditTransactionTransactionId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.CreditWallet", b =>
                {
                    b.HasOne("AssistenteExecutivo.Domain.Entities.UserProfile", null)
                        .WithOne()
                        .HasForeignKey("AssistenteExecutivo.Domain.Entities.CreditWallet", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.MediaAsset", b =>
                {
                    b.OwnsOne("AssistenteExecutivo.Domain.ValueObjects.MediaRef", "MediaRef", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetMediaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("Hash");

                            b1.Property<string>("MimeType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("MimeType");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("SizeBytes");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("StorageKey");

                            b1.HasKey("MediaAssetMediaId");

                            b1.ToTable("MediaAssets");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetMediaId");
                        });

                    b.Navigation("MediaRef")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Note", b =>
                {
                    b.HasOne("AssistenteExecutivo.Domain.Entities.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Plan", b =>
                {
                    b.OwnsOne("AssistenteExecutivo.Domain.ValueObjects.PlanLimits", "Limits", b1 =>
                        {
                            b1.Property<Guid>("PlanId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("Contacts")
                                .HasColumnType("integer")
                                .HasColumnName("LimitsContacts");

                            b1.Property<int?>("CreditsPerMonth")
                                .HasColumnType("integer")
                                .HasColumnName("LimitsCreditsPerMonth");

                            b1.Property<int?>("Notes")
                                .HasColumnType("integer")
                                .HasColumnName("LimitsNotes");

                            b1.Property<decimal?>("StorageGB")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("LimitsStorageGB");

                            b1.HasKey("PlanId");

                            b1.ToTable("Plans");

                            b1.WithOwner()
                                .HasForeignKey("PlanId");
                        });

                    b.Navigation("Limits")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Relationship", b =>
                {
                    b.HasOne("AssistenteExecutivo.Domain.Entities.Contact", null)
                        .WithMany("Relationships")
                        .HasForeignKey("SourceContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssistenteExecutivo.Domain.Entities.Contact", null)
                        .WithMany()
                        .HasForeignKey("TargetContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.UserProfile", b =>
                {
                    b.OwnsOne("AssistenteExecutivo.Domain.ValueObjects.PersonName", "DisplayName", b1 =>
                        {
                            b1.Property<Guid>("UserProfileUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("LastName");

                            b1.HasKey("UserProfileUserId");

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileUserId");
                        });

                    b.OwnsOne("AssistenteExecutivo.Domain.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserProfileUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("Email");

                            b1.HasKey("UserProfileUserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileUserId");
                        });

                    b.OwnsOne("AssistenteExecutivo.Domain.ValueObjects.KeycloakSubject", "KeycloakSubject", b1 =>
                        {
                            b1.Property<Guid>("UserProfileUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("KeycloakSubject");

                            b1.HasKey("UserProfileUserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileUserId");
                        });

                    b.Navigation("DisplayName")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("KeycloakSubject")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Workflow", b =>
                {
                    b.OwnsOne("AssistenteExecutivo.Domain.ValueObjects.WorkflowTrigger", "Trigger", b1 =>
                        {
                            b1.Property<Guid>("WorkflowId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ConfigJson")
                                .HasColumnType("jsonb")
                                .HasColumnName("TriggerConfigJson");

                            b1.Property<string>("CronExpression")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("TriggerCronExpression");

                            b1.Property<string>("EventName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("TriggerEventName");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("TriggerType");

                            b1.HasKey("WorkflowId");

                            b1.ToTable("Workflows");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowId");
                        });

                    b.Navigation("Trigger")
                        .IsRequired();
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.Contact", b =>
                {
                    b.Navigation("Relationships");
                });

            modelBuilder.Entity("AssistenteExecutivo.Domain.Entities.CreditWallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
